import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { Main } from '@/components/Main'
import {
  useAddress,
  useMetamask,
  useLogin,
  useLogout,
  useUser,
} from "@thirdweb-dev/react";

const inter = Inter({ subsets: ['latin'] })

const getOnlineStatus = () => {
  return typeof navigator !== 'undefined' && typeof navigator.onLine === 'boolean'
    ? navigator.onLine
    : true
}

const useNavigatorOnLine = () => {
  const [isOnline, setIsOnline] = useState<boolean>(getOnlineStatus())

  const handleOnline = () => setIsOnline(true)

  const handleOffline = () => setIsOnline(false)

  


  useEffect(() => {
    window.addEventListener('online', handleOnline)
    window.addEventListener('offline', handleOffline)

    return () => {
      window.removeEventListener('online', handleOnline)
      window.removeEventListener('offline', handleOffline)
    }

  }, [])

  return isOnline
}

export default function Home() {

  const address = useAddress();
  const connect = useMetamask();
  const { login } = useLogin();
  const { logout } = useLogout();
  const { user, isLoggedIn } = useUser();
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")

  const isOnline = useNavigatorOnLine()


  const handleLogin = () => {
    // All of these fields are optional
    login({
      uri: "https://localhost:4000/api/auth",
      statement: "Please agree to our terms of service!",
      chainId: "97",
      nonce: "123",
      version: "1",
      resources: ["https://tos.example.com"],
    })
  }

  const handleLogout = () => {
    fetch("http://localhost:4000/api/auth/logout", {
      method: "POST",
      credentials: "include",
    })
      .then((res) => res.json())
      .then((res) => {
        logout();
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      });
  }

  useEffect(() => {
    setLoading(true)

    setTimeout(() => {
      if (!isOnline) {
        setError('You are offline')
        setLoading(false)
        return
      } else {
        fetch('http://localhost:4000/api', {
          // credentials: 'include',
        })
          .then(response => response.json())
          .then(json => {
            console.log(json)
          })
          .catch(error => {
            console.log(error)
          })
        fetch('https://jsonplaceholder.typicode.com/todos')
          .then(response => response.json())
          .then(json => {
            setData(json)
            setLoading(false)
          })
          .catch(error => {
            if (isOnline) {
              setError(error.toString())
            } else {
              setError('You are offline')
            }

          })
          .finally(() => setLoading(false))
      }
    }, 2000)
  }, [isOnline])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Main/>
        <div className={styles.description}>
          <p>
            A progressive webApp&nbsp;
            <code className={styles.code}> to check offline load</code>
          </p>
          <div>
      {isLoggedIn ? (
        <button onClick={() => handleLogout()}>Logout</button>
      ) : address ? (
        <button onClick={() => handleLogin()}>Login</button>
      ) : (
        <button onClick={() => connect()}>Connect</button>
      )}

      <pre>Connected Wallet: {address}</pre>
      <pre>User: {user ? user.data : "N/A"}</pre>
    </div>
        </div>
        {loading && <p>Loading...</p>}
        {error && <p>{error}</p>}
        {!loading && !error && <div className={styles.grid}>
          {data.map((item: any, index) => (
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              key={index}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                {item.title} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Find in-depth information about Next.js features and&nbsp;API.
              </p>
            </a>


          ))}
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>}
      </main>
    </>
  )
}
